### ISSUE TITLE
Autumn Forest Cave Shortcut

### ISSUE THREAD

**Issue by Lizband** [Neverway/GM-DivineAnnihilation#22]
A proper level needs to be designed for the cave shortcut in the Autumn forest section of the game. This section of the game is supposed to be fairly easy. Enemies that will appear there will be things such as the Salt-Water Bat and Viper Spider.

**Comment by Snakea505** [comment]
I will do this one

**Comment by Snakea505** [comment]
I have created a basic design of the level
